In [1]:
import pandas as pd
import datetime as dt
from src.tasks import BondsDescription

In [2]:
pos_df = pd.concat( pd.read_excel(fr'C:\Users\SSamoliuk\Downloads\Bond PnL Report_FI_{entity}_2026-02-27.xlsx', skiprows=1).assign(Entity=entity) for entity in ['NRBM', 'CAAC'] )
pos_df['vol_bio'] = (pos_df['Quantity'] * 1e-6).round(2)

In [3]:
desc_df = BondsDescription(date=dt.date.today()).read_output()

In [4]:
pos_df[pos_df['Isin'].isin(desc_df['ISIN'])]['Portfolio'].value_counts()

Portfolio
NRBM_FI_Bonds_OFZ_Trd    33
NRBM_FI_FX_OFZ           10
CAAC_FI_Bonds_OFZ_Trd     9
CAAC_FI_FX_OFZ            5
CAAC_FI_Bonds_TRD_HTM     3
NRBM_FI_Bonds_AFS         1
Name: count, dtype: int64

In [15]:
df = (desc_df.reset_index().set_index('ISIN', verify_integrity=True)[['secid', 'series', 'SHORT_TYPE']].sort_values('series')
    .join(pos_df.groupby('Isin')['vol_bio'].sum())
    .join(pos_df.groupby('Isin')[['Entity', 'Portfolio', 'vol_bio']].apply(lambda x: x.set_index(['Portfolio'])['vol_bio'].to_dict()).to_frame('split')))

In [20]:
df.query('series == 26247')

,secid,series,SHORT_TYPE,vol_bio,split
ISIN,,,,,
RU000A108EF8,SU26247RMFS5,26247,фикс. купон,-3.5,{'NRBM_FI_Bonds_OFZ_Trd': -3.5}

In [16]:
pd.set_option('display.max_colwidth', None)
df.nsmallest(10, 'vol_bio')

,secid,series,SHORT_TYPE,vol_bio,split
ISIN,,,,,
RU000A102BT8,SU26236RMFS8,26236,фикс. купон,-50.27,"{'NRBM_FI_FX_OFZ': 12.3, 'NRBM_FI_Bonds_OFZ_Trd': -110.57, 'CAAC_FI_Bonds_OFZ_Trd': 48.0}"
RU000A1014N4,SU26232RMFS7,26232,фикс. купон,-16.62,{'NRBM_FI_Bonds_OFZ_Trd': -16.62}
RU000A108EH4,SU26248RMFS3,26248,фикс. купон,-11.36,{'NRBM_FI_Bonds_OFZ_Trd': -11.36}
RU000A108EF8,SU26247RMFS5,26247,фикс. купон,-3.50,{'NRBM_FI_Bonds_OFZ_Trd': -3.5}
RU000A100EF5,SU26230RMFS1,26230,фикс. купон,-3.40,{'NRBM_FI_Bonds_OFZ_Trd': -3.4}
RU000A1038V6,SU26238RMFS4,26238,фикс. купон,-0.40,{'NRBM_FI_Bonds_OFZ_Trd': -0.4}
RU000A1074G2,SU26244RMFS2,26244,фикс. купон,-0.23,{'NRBM_FI_Bonds_OFZ_Trd': -0.23}
RU000A101F94,SU26233RMFS5,26233,фикс. купон,-0.05,{'NRBM_FI_Bonds_OFZ_Trd': -0.05}
RU000A0JS3W6,SU26207RMFS9,26207,фикс. купон,0.00,{'NRBM_FI_Bonds_OFZ_Trd': -0.0}
RU000A0JVW48,SU26218RMFS6,26218,фикс. купон,0.00,{'NRBM_FI_Bonds_OFZ_Trd': 0.0}

In [17]:
df.nlargest(10, 'vol_bio')

,secid,series,SHORT_TYPE,vol_bio,split
ISIN,,,,,
RU000A10CKT3,SU26251RMFS7,26251,фикс. купон,107.39,"{'NRBM_FI_Bonds_OFZ_Trd': 49.99, 'NRBM_FI_FX_OFZ': 57.4}"
RU000A10BVC8,SU26249RMFS1,26249,фикс. купон,73.82,"{'NRBM_FI_FX_OFZ': 19.9, 'NRBM_FI_Bonds_OFZ_Trd': 13.92, 'CAAC_FI_Bonds_OFZ_Trd': 40.0}"
RU000A105RV3,SU26242RMFS6,26242,фикс. купон,36.53,"{'NRBM_FI_Bonds_OFZ_Trd': 3.89, 'NRBM_FI_FX_OFZ': 32.64, 'CAAC_FI_Bonds_OFZ_Trd': 0.0}"
RU000A10D4Y2,SU26252RMFS5,26252,фикс. купон,28.81,"{'NRBM_FI_Bonds_OFZ_Trd': 17.81, 'NRBM_FI_FX_OFZ': 11.0}"
RU000A0JV4M0,SU29007RMFS0,29007,флоутер,27.09,"{'NRBM_FI_Bonds_OFZ_Trd': 0.45, 'CAAC_FI_FX_OFZ': 1.54, 'CAAC_FI_Bonds_OFZ_Trd': 25.1}"
RU000A0ZYUA9,SU26224RMFS4,26224,фикс. купон,21.40,"{'NRBM_FI_Bonds_OFZ_Trd': 0.0, 'NRBM_FI_FX_OFZ': 0.0, 'CAAC_FI_FX_OFZ': 12.85, 'CAAC_FI_Bonds_OFZ_Trd': 8.55}"
RU000A0ZYZ26,SU52002RMFS1,52002,ипц-линкер,20.86,"{'NRBM_FI_FX_OFZ': 0.0, 'NRBM_FI_Bonds_OFZ_Trd': 0.11, 'CAAC_FI_Bonds_OFZ_Trd': 11.75, 'CAAC_FI_FX_OFZ': 9.0}"
RU000A0JV4P3,SU29008RMFS8,29008,флоутер,11.68,"{'NRBM_FI_FX_OFZ': 0.0, 'NRBM_FI_Bonds_OFZ_Trd': 0.0, 'CAAC_FI_FX_OFZ': 0.5, 'CAAC_FI_Bonds_OFZ_Trd': 11.18}"
RU000A0JXFM1,SU26221RMFS0,26221,фикс. купон,5.03,{'NRBM_FI_Bonds_OFZ_Trd': 5.03}
RU000A108EG6,SU26245RMFS9,26245,фикс. купон,4.73,"{'NRBM_FI_Bonds_OFZ_Trd': 1.29, 'NRBM_FI_FX_OFZ': 0.0, 'CAAC_FI_FX_OFZ': 3.44, 'CAAC_FI_Bonds_OFZ_Trd': 0.0}"